export const SHOW_PICTURE_SELECTED = 'SHOW_PICTURE_SELECTED';
export const HIDE_PICTURES_SELECTED = 'HIDE_PICTURES_SELECTED';
export const GET_PICTURES_FROM_FILE_REQUEST = 'GET_PICTURES_FROM_FILE_REQUEST';
export const GET_PICTURES_FROM_FILE_SUCCESS = 'GET_PICTURES_FROM_FILE_SUCCESS';
export const COUNT_SCORE_GAME = 'COUNT_SCORE_GAME';
