export const SAVE_USER_RESULT_REQUEST = 'SAVE_USER_RESULT_REQUEST';
export const SAVE_USER_RESULT_SUCCES = 'SAVE_USER_RESULT_SUCCES';
export const GET_USERS_RESULTS_REQUEST = 'GET_USERS_RESULTS_REQUEST';
export const GET_USERS_RESULTS_SUCCESS = 'GET_USERS_RESULTS_SUCCESS';
export const CHANGE_SAVED_RESULT_STATUS = 'CHANGE_SAVED_RESULT_STATUS';

